Here goes another nothing

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 
+## VARIABLES
+RUN_COMMAND=run_tor
+TOR_VER=0.4.1.6
+TOR_SRC_NAME=tor-${TOR_VER}.tar.gz
+TOR_DIST_URL=https://www.torproject.org/dist/
+
+
+## --
+
+set -x
+
 indent() {
     sed -u 's/^/      /'
 }
@@ -7,49 +18,92 @@ indent() {
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
+TOR_SIG_NAME=${TOR_SRC_NAME}.asc
+TOR_SRC_URL=${TOR_DIST_URL}${TOR_SRC_NAME}
+TOR_SRC_SIG_URL=${TOR_DIST_URL}${TOR_SIG_NAME}
 
-if [[ -e "${ENV_DIR}/TOR_SRC_URL" ]]; then
-    TOR_SRC_URL=$(cat ${ENV_DIR}/TOR_SRC_URL)
+################################################################################
+# Try use cache
+################################################################################
+mkdir -p $CACHE_DIR
+grep -wq "${TOR_SRC_NAME}" $CACHE_DIR/tor_version.txt
+if [ $? -eq 0 ] ; then # Reusing cache
+   TOR_IS_CACHED=1
+else
+   TOR_IS_CACHED=0
 fi
 
-if [[ -z "${TOR_SRC_URL}" ]]; then
-    TOR_SRC_URL="https://www.torproject.org/dist/tor-0.4.1.6.tar.gz"
+################################################################################
+# GET SOURCES
+################################################################################
+if [ $TOR_IS_CACHED -eq 0 ] ; then
+    echo "Downloading ${TOR_SRC_URL}"
+    wget -q $TOR_SRC_URL
+
+    if [ $? - ne 0]; then
+        echo "FAILED to obtain ${TOR_SRC_URL}" | indent
+        exit 1
+    fi
+
+    echo "Downloading ${TOR_SRC_SIG_URL}"
+    wget -q $TOR_SRC_SIG_URL
+
+    if [ $? -ne 0 ]; then
+        echo "FAILED to obtain signature ${TOR_SRC_SIG_URL}" | indent
+        exit 1
+    fi
 fi
+################################################################################
+# VERIFY INTEGRITY
+################################################################################
+# if [ $TOR_IS_CACHED -eq 0 ] ; then
+#     gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
+#     gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6AFEE6D49E92B601
+#     gpg --verify ${TOR_SIG_NAME} ${TOR_SRC_NAME} | grep -c "Good signature"
+#     if [ $? -lt 1 ]; then
+#         echo "FAILED to verify the signature" | indent
+#         exit 1
+#     fi
+# fi
+################################################################################
+# COMPILE
+################################################################################
+if [ $TOR_IS_CACHED -eq 0 ] ; then
+    tar -zxf ${TOR_SRC_NAME}
+    cd tor-${TOR_VER}
+    ./configure --prefix=$CACHE_DIR/tor
+    if [ $? -ne 0 ]; then
+        echo "FAILED to configure for compliation" | indent
+        exit 1
+    fi
 
-wget -q $TOR_SRC_URL
-
-if ! [ $? ]; then
-    echo "FAILED to obtain tor src" | indent
-    exit 1
+    make install
+    if [ $? -ne 0 ]; then
+        echo "FAILED to run make install" | indent
+        exit  1
+    fi
 fi
+################################################################################
+# INSTALL
+################################################################################
 
-# Finally do some compilation.
-tar -zxf tor-*.tar.gz
-cd tor-*
-./configure --prefix=$BUILD_DIR
-if ! [ $? ]; then
-    echo "FAILED to configure for compliation" | indent
-    exit 1
-fi
+# Cached installation to real build dir
+cp -r $CACHE_DIR/tor ${BUILD_DIR}
 
-make install
-if ! [ $? ]; then
-    echo "FAILED to run make install" | indent
-fi
+# Saves the version just compiled
+echo "${TOR_SRC_NAME}" > $CACHE_DIR/tor_version.txt
 
-# Cache builds to avoid unnecessary wait times.
-echo $TOR_SRC_URL > $CACHE_DIR/.src-dist
-
-cat > ${BUILD_DIR}/bin/hide <<EOF
+cat > ${BUILD_DIR}/tor/bin/${RUN_COMMAND} <<EOF
 #!/usr/bin/env bash
-echo "ControlPort 9051" > $HOME/etc/tor/torrc
-echo "CookieAuthentication 0" >> $HOME/etc/tor/torrc
-
+mkdir -p "${HOME}/hidden_service"
+echo "Setting up tor"
+echo "ControlPort 9051" > $HOME/tor/etc/tor/torrc
+echo "CookieAuthentication 0" >> $HOME/tor/etc/tor/torrc
 # Use -f to be safe here.
-$HOME/bin/tor -f $HOME/etc/tor/torrc &
+$HOME/tor/bin/tor -f $HOME/tor/etc/tor/torrc &
 exec \$*
 EOF
 
-chmod a+x ${BUILD_DIR}/bin/hide
+chmod a+x ${BUILD_DIR}/tor/bin/${RUN_COMMAND}
 
 echo "Installed Tor successfully" | indent
